# Generated by Django 4.0.3 on 2022-05-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_cliente',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagenes_post', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagenes_productos', verbose_name='Imagen'),
        ),
    ]
