# Generated by Django 4.0.3 on 2022-05-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_alter_post_cliente_imagen_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_cliente',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagenes_post/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagenes_producto/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(blank=True, verbose_name='Precio'),
        ),
    ]
