# Generated by Django 4.0.3 on 2022-05-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_alter_post_cliente_imagen_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_cliente',
            name='categoria',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Comida'), (2, 'Hogar'), (3, 'Informatica'), (4, 'Moda'), (5, 'Servicios'), (6, 'Vehiculos'), (7, 'Otros')], default=5, verbose_name='Categoria Post'),
        ),
        migrations.AlterField(
            model_name='post_cliente',
            name='num_likes',
            field=models.IntegerField(blank=True, default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='post_cliente',
            name='opinion',
            field=models.CharField(blank=True, max_length=500, verbose_name='Opinion dada por el cliente'),
        ),
    ]
