# Generated by Django 4.0.3 on 2022-05-26 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0008_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_cliente',
            name='producto',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='series.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post_cliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to='series.cliente'),
        ),
    ]
