# Generated by Django 4.0.3 on 2022-05-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0009_post_cliente_producto_alter_post_cliente_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='series/static/img/imagenes_producto/no-product-image.png', upload_to='series/static/img/imagenes_producto', verbose_name='Imagen del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(blank=True, default='', null=True, verbose_name='Precio del producto'),
        ),
    ]
