# Generated by Django 4.0.3 on 2022-05-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0010_alter_producto_imagen_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.CharField(blank=True, default='Sin precio', max_length=10, null=True, verbose_name='Precio del producto'),
        ),
    ]
