# Generated by Django 4.0.3 on 2022-05-29 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0011_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_cliente',
            name='titulo',
        ),
    ]
