# Generated by Django 4.0.3 on 2022-05-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0012_remove_post_cliente_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=25, unique=True, verbose_name='Nombre producto'),
        ),
    ]
