# Generated by Django 4.0.3 on 2022-05-30 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0013_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_cliente',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to='series.cliente'),
        ),
        migrations.AlterField(
            model_name='post_cliente',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='series.producto'),
        ),
    ]
