# Generated by Django 4.0.4 on 2022-05-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0014_alter_post_cliente_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='series/static/img/imagenes_clientes', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='series/static/img/imagenes_empresa', verbose_name='Imagen corporativa de la empresa'),
        ),
    ]
